### ISSUE TITLE
improve relay-example, usePagination for todos

### ISSUE THREAD

**Issue by morrys** [relay-tools/relay-hooks#1]
Integrate the "relay-example" with usePagination.

**Comment by sandeepone** [comment]
Any points on how to add Previous and Next pagination in UI. 
The result data is merged from usePagination or useRefetchable  and hasPreviousPage is always false and list all results

Thanks in advance

**Comment by morrys** [comment]
Hi @sandeepone,
these links might help you:

https://github.com/facebook/relay/issues/540
https://artsy.github.io/blog/2020/01/21/graphql-relay-windowed-pagination/

**Comment by sandeepone** [comment]
@morrys Thank you.
Seems like relay store merges the data instead of slice of values for UI. Maybe I should try without hooks (createRefetchContainer)

**Comment by morrys** [comment]
useRefetch & createRefetchContainer are the same, this problem is not related to the use of HOCs or hooks.

Anyway you can try using the HOC and then try the hook again

**Comment by sandeepone** [comment]
@morrys you're right, most of the examples uses createRefetchContainer so i thought its related to it. 

Its mentioned in Relay experimental docs that any update across the app will merge the results of the query with all the items. So in order to do previous/next pagination i need ```Custom Connection State``` for Visually separating each page of items

https://relay.dev/docs/en/experimental/a-guided-tour-of-relay#custom-connection-state

**Comment by morrys** [comment]
Issue resolved with relay-hooks version [4.0.0](https://github.com/relay-tools/relay-hooks/releases/tag/v4.0.0)
