### ISSUE TITLE
FragmentPagination.ts: fragmentOwner is null after migrating from 0.3.0 to 1.1.0

### ISSUE THREAD

**Issue by jazblueful** [relay-tools/relay-hooks#9]
After migrating from 0.3.0 to 1.1.0, I'm getting: **Uncaught TypeError: Cannot read property 'variables' of null** at https://github.com/relay-tools/relay-hooks/blob/master/src/FragmentPagination.ts#L398 when executing loadMore function of usePagination hook.

useFragment with refetch in version 0.3.0 used to work fine.

My code is almost identical the one show in the example https://github.com/relay-tools/relay-hooks/blob/master/usePagination.md so I'm not going to post it here for now.

Thank you for looking into this issue.

**Comment by morrys** [comment]
hi jazblueful,
thanks for reporting, as soon as possible I will verify this error in order to release its fix together with the optimizations.

Since version 0.3.0 I have made major changes to the project.

Later it would be useful to make a pagination in the todo project (at the moment I can't implement it due to lack of time)

**Comment by jazblueful** [comment]
Thank you :)

**Comment by morrys** [comment]
hi jazblueful,
I just released version 1.2.0 of relay-hooks.

Now the server-side behavior of useQuery is identical to that of the QueryRenderer and I solved the usePagination.

I hope we return optimistically after this issue :D

I'm waiting for your news to close the issue.

Thank you,
Lorenzo

**Comment by jazblueful** [comment]
Awesome! It's working perfectly now, both client- and server side.

Thank you Lorenzo
